### PR TITLE
Correctly set Google IAP validation env

### LINKED ISSUE #778: Google purchase validation purchase environment is UNKNOWN
## Description
 ValidatedPurchaseEnvironment variable always returns UNKOWN for both sandbox and live in-app purchases on validating purchases from google play store .

## Steps to Reproduce
1. Purchase a sandbox or live in app purchase from google playstore using actual android device
2. Use purchase validation google api provided by nakama
3. IAP validation succeeds but ValidatedPurchaseEnvironment is returned as unkown

## Expected Result
ValidatedPurchaseEnvironment should be either Sandbox or Production  instead of Unknown  

## Actual Result
ValidatedPurchaseEnvironment == Unknown . 

## Context
- [ ] Unity

## Your Environment
- Nakama: v3.9.0-r1-mc+6583f7b
- Environment name and version: Deployed on nakama cloud using typescript language
- Operating System and version: reproduced on multiple android devices

### PR DESCRIPTION
**Pull request by sesposito**
Resolves #778

### CODE REVIEW

File: iap/iap.go [hunk 1]
```diff
@@ -386,6 +386,7 @@ func validateReceiptGoogleWithIDs(ctx context.Context, httpc *http.Client, token
 	switch resp.StatusCode {
 	case 200:
 		out := &ValidateReceiptGoogleResponse{}
+		out.PurchaseType = -1 // Set sentinel value as this field is omitted in production, and if set to 0 it means the purchase was done in sandbox env
```
Comment (zyro) [inline iap/iap.go:389]: @sesposito Let's speak more about this.

**Review by zyro — CHANGES_REQUESTED** [review]

**Review by zyro — APPROVED** [review]
